from BaseClasses import Location

class MGSLocation(Location):
    game: str = 'Metal Gear Solid'

base_mgs_location_id = 69 # nice.

location_names = [
    'Cardboard Box A',
    'Cardboard Box B',
    'Cardboard Box C',
    'Night Vision Goggles',
    'Thermal Goggles',
    'Gas Mask',
    'Body Armor',
    # 'Ketchup',
    # 'Camera',
    'Ration 1',
    'Ration 2',
    'Ration 3',
    'Ration 4',
    'Ration 5',
    'Ration 6',
    'Ration 7',
    'Ration 8',
    'Ration 9',
    'Ration 10',
    'Ration 11',
    'Ration 12',
    'Ration 13',
    'Ration 14',
    'Ration 15',
    'Ration 16',
    'Ration 17',
    'Ration 18',
    'Ration 19',
    'Ration 20',
    'Ration 21',
    'Ration 22',
    'Ration 23',
    'Ration 24',
    'Ration 25',
    'Ration 26',
    'Ration 27',
    'Ration 28',
    'Ration 29',
    'Ration 30',
    'Ration 31',
    'Ration 32',
    'Ration 33',
    'Ration 34',
    'Ration 35',
    'Ration 36',
    'Ration 37',
    'Ration 38',
    'Ration 39',
    'Ration 40',
    'Ration 41',
    'Ration 42',
    'Ration 43',
    'Medicine 1',
    'Diazepam 1',
    'Diazepam 2',
    'Diazepam 3',
    'Pal Key',
    'Key Card Level 1',
    'Key Card Level 2',
    'Key Card Level 3',
    'Key Card Level 4',
    'Key Card Level 5',
    'Key Card Level 6',
    'Key Card Level 7',
    'Time Bomb 1',
    'Mine Detector',
    # 'Disc',
    'Rope',
    'Handkerchief',
    'Suppressor',
    'SOCOM 1',
    'SOCOM 2',
    'SOCOM 3',
    'SOCOM 4',
    'SOCOM 5',
    'SOCOM 6',
    'SOCOM 7',
    'SOCOM 8',
    'SOCOM 9',
    'SOCOM 10',
    'SOCOM 11',
    'SOCOM 12',
    'SOCOM 13',
    'SOCOM 14',
    'SOCOM 15',
    'SOCOM 16',
    'SOCOM 17',
    'SOCOM 18',
    'SOCOM 19',
    'SOCOM 20',
    'SOCOM 21',
    'SOCOM 22',
    'SOCOM 23',
    'SOCOM 24',
    'SOCOM 25',
    'SOCOM 26',
    'SOCOM 27',
    'SOCOM 28',
    'SOCOM 29',
    'SOCOM 30',
    'SOCOM 31',
    'SOCOM 32',
    'SOCOM 33',
    'SOCOM 34',
    'SOCOM 35',
    'SOCOM 36',
    'SOCOM 37',
    'SOCOM 38',
    'FA-MAS 1',
    'FA-MAS 2',
    'FA-MAS 3',
    'FA-MAS 4',
    'FA-MAS 5',
    'FA-MAS 6',
    'FA-MAS 7',
    'FA-MAS 8',
    'FA-MAS 9',
    'FA-MAS 10',
    'FA-MAS 11',
    'FA-MAS 12',
    'FA-MAS 13',
    'FA-MAS 14',
    'FA-MAS 15',
    'FA-MAS 16',
    'FA-MAS 17',
    'FA-MAS 18',
    'FA-MAS 19',
    'FA-MAS 20',
    'FA-MAS 21',
    'FA-MAS 22',
    'FA-MAS 23',
    'FA-MAS 24',
    'FA-MAS 25',
    'FA-MAS 26',
    'FA-MAS 27',
    'FA-MAS 28',
    'FA-MAS 29',
    'FA-MAS 30',
    'FA-MAS 31',
    'FA-MAS 32',
    'FA-MAS 33',
    'FA-MAS 34',
    'FA-MAS 35',
    'FA-MAS 36',
    'FA-MAS 37',
    'FA-MAS 38',
    'FA-MAS 39',
    'FA-MAS 40',
    'FA-MAS 41',
    'FA-MAS 42',
    'FA-MAS 43',
    'FA-MAS 44',
    'FA-MAS 45',
    'FA-MAS 46',
    'Grenade 1',
    'Grenade 2',
    'Grenade 3',
    'Grenade 4',
    'Grenade 5',
    'Grenade 6',
    'Grenade 7',
    'Grenade 8',
    'Grenade 9',
    'Grenade 10',
    'Grenade 11',
    'Nikita 1',
    'Nikita 2',
    'Nikita 3',
    'Nikita 4',
    'Nikita 5',
    'Nikita 6',
    'Nikita 7',
    'Nikita 8',
    'Nikita 9',
    'Nikita 10',
    'Nikita 11',
    'Nikita 12',
    'Nikita 13',
    'Nikita 14',
    'Stinger 1',
    'Stinger 2',
    'Stinger 3',
    'Stinger 4',
    'Stinger 5',
    'Stinger 6',
    'Stinger 7',
    'Stinger 8',
    'Stinger 9',
    'Stinger 10',
    'Stinger 11',
    'Stinger 12',
    'Stinger 13',
    'Stinger 14',
    'Stinger 15',
    'Stinger 16',
    'Stinger 17',
    'Claymore 1',
    'Claymore 2',
    'Claymore 3',
    'Claymore 4',
    'Claymore 5',
    'Claymore 6',
    'Claymore 7',
    'Claymore 8',
    'Claymore 9',
    'C4 1',
    'C4 2',
    'C4 3',
    'C4 4',
    'C4 5',
    'Stun Grenade 1',
    'Stun Grenade 2',
    'Stun Grenade 3',
    'Stun Grenade 4',
    'Stun Grenade 5',
    'Stun Grenade 6',
    'Stun Grenade 7',
    'Stun Grenade 8',
    'Stun Grenade 9',
    'Chaff Grenade 1',
    'Chaff Grenade 2',
    'Chaff Grenade 3',
    'Chaff Grenade 4',
    'Chaff Grenade 5',
    'Chaff Grenade 6',
    'Chaff Grenade 7',
    'Chaff Grenade 8',
    'Chaff Grenade 9',
    'Chaff Grenade 10',
    'Chaff Grenade 11',
    'Chaff Grenade 12',
    'Chaff Grenade 13',
    'Chaff Grenade 14',
    'Chaff Grenade 15',
    'PSG-1 1',
    'PSG-1 2',
    'PSG-1 3',
    'PSG-1 4',
    'PSG-1 5',
    'PSG-1 6',
    'PSG-1 7',
    'PSG-1 8',
    'PSG-1 9',
    'PSG-1 10',
    'PSG-1 11',
    'PSG-1 12',
    'PSG-1 13',
    'PSG-1 14',
    'PSG-1 15',
    'PSG-1 16',
    'PSG-1 17',
    'PSG-1 18',
    'BOSS: Heavily Armed Genome Soldiers',
    'BOSS: Revolver Ocelot',
    'BOSS: M1 Tank',
    'BOSS: Gray Fox',
    'BOSS: Psycho Mantis',
    'BOSS: Sniper Wolf I',
    'BOSS: Black-outfitted Genome Soldiers I',
    'BOSS: A Hind D?',
    'BOSS: Stealth Camouflaged Genome Soldiers',
    'BOSS: Sniper Wolf II',
    'BOSS: Black-outfitted Genome Soldiers II',
    'BOSS: Vulcan Raven',
    'BOSS: Metal Gear REX',
    'BOSS: Liquid Snake',
    'The Best is Yet to Come'
]

location_name_to_id_table = dict([(name, i+base_mgs_location_id) for (i, name) in enumerate(location_names)])